### ISSUE TITLE
Comments on design docs 

### ISSUE THREAD

**Issue by cindyytong** [sharshi/Morning-Dash#9]
For MVPs:
1. Add features: user onboarding & settings with following:  
a. A user should be able to sign up and set up their location, link their google calendar and set up their daily commute (set home and work) 
2. I don't understand what the Timeline feature will be doing. Do you have a wireframe of this. 
3. For all cases where we are loading info from an API, we should design a fail situation where you don't get any data back from the api endpoint. 
4. For each feature please write specific user stories. 

5. Wireframes: Let's get these included in your wiki. Each wireframe should list out FE routes, BE endpoints needed, names of components used and specific user stories they link to.

6. Work breakdown: This is great, please use some kind of trello/ github tracker. I also recommend that you each pair up and provide reviews for the other throughout. 

7. Technologies and APIs
- apply for all the apis now if possible 
- think about how often you are going to be fetching from the APIs and if there are limitations on the APIs on requests you can make 

8. Add front end state 
Schema 
BE routes 

9. Design lead should make a design style guide which will standardize what the fonts, colors, button sizes, etc should be throughout. This doesn't have to be fancy but everyone on team should be aware. Here are some good examples: http://styleguides.io/

**Comment by sharshi** [comment]
@cindyytong 6 is here: https://github.com/sharshi/Morning-Dash/projects/1 
@sharshi assigned 1, 3,
@RazEfron assigned 8, 4
@lifesscholar assigned 2, 7
@al6 assigned 9

**Comment by lifesscholar** [comment]
2. Removed the Timeline from our MVPs. It was from a previous version of our app.
7.  We've signed up for all three of our API keys. 
     The DarkSkyAPI has 1000 calls per day for free.
     The Google Directions API we have a global limit of unlimited and a limit per ms of 5000
     The Google Calendar API is similar to the Directions API.

**Comment by sharshi** [comment]
Wireframes from neev
![sign-up-form-1](https://user-images.githubusercontent.com/4740525/75299008-efd2c280-5801-11ea-9f69-027d4ee1f770.png)
![Screen_1](https://user-images.githubusercontent.com/4740525/75299009-f06b5900-5801-11ea-86f0-c199ba614382.png)
![sign-up-form-2](https://user-images.githubusercontent.com/4740525/75299010-f06b5900-5801-11ea-81b2-df4b87660fdb.png)

**Comment by sharshi** [comment]
filled out the technologies page including the APIS and their limitations:
https://github.com/sharshi/Morning-Dash/wiki/Technologies-and-Technical-Challenges 
[Backend-Routes](https://github.com/sharshi/Morning-Dash/wiki/Backend-Routes), [Sample-State](https://github.com/sharshi/Morning-Dash/wiki/Sample-State), and [Overview / user stories](https://github.com/sharshi/Morning-Dash/wiki/Background-and-Overview) are in progress and will be completed tomorrow morning.

**Comment by sharshi** [comment]
lastly: https://github.com/sharshi/Morning-Dash/pull/15 from @al6 includes design info

**Comment by RazEfron** [comment]
backend routes done
